name: 'Fast Forward Merge'
description: 'Merge a pull request by fast forwarding the target branch.'
author: 'Sequoia PGP'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
runs:
  using: "composite"
  steps:
    # github.action_path is set to $REPO/fast-forward.
    - run: |
        GITHUB_TOKEN=${{ inputs.github_token }} \
          ${{ github.action_path }}/../src/fast-forward.sh --merge
      shell: bash
branding:
  icon: 'arrow-up-right'
  color: 'green'
